// Generated by Wrangler on Tue Aug 20 2024 15:25:31 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  harvest_last_entry_id: KVNamespace;
  linear_issue_tracked_time: KVNamespace;
  HARVEST_API_KEY: string;
  LINEAR_API_KEY: string;
  HARVEST_ACCOUNT_ID: string;
}
