// Generated by Wrangler on Tue Aug 20 2024 09:45:57 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
  harvest_last_entry_id: KVNamespace;
  HARVEST_API_KEY: string;
  LINEAR_API_KEY: string;
  HARVEST_ACCOUNT_ID: string;
}
